### ISSUE TITLE
Error - Export start failed

### ISSUE THREAD

**Issue by johnbernardhenry** [biblibre/omeka-plugin-Export#1]
Trying to export to a .csv and getting the error "Export start failed" yet it still shows as queued. Where might my error be? 

![image](https://user-images.githubusercontent.com/79190245/109873299-6a5acd00-7c22-11eb-973a-de409e24facf.png)

**Comment by jajm** [comment]
I guess the problem is probably in your config file (`application/config/config.ini`). See https://omeka.org/classic/docs/Technical/Setting_PHP_Path/

To be sure, I added a new commit (491c4d04e3707c83fe9c2e215635524919b4b8f4) that displays the underlying error message. It fixes the problem with the export status too. Please update to the latest version and retry.

**Comment by johnbernardhenry** [comment]
Thank you!
